package com.example.easynotes.model;

public enum Role {
	DRINKFORMS,ENDOFTHEDAYFORMS,ICECREAMFORMS,ORDERS,CUSTOMERSERVICEEMPLOYEES,SHIFTSUPERVISORS,PART,TOTALITY,SPECIALSITUATIONS,PRODUCTS,CREATEDJUICE
}
